// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzyuhwgltenkeclnpgfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6eXVod2dsdGVua2VjbG5wZ2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzYyNTMsImV4cCI6MjA3MTU1MjI1M30.7o-Z2mxvexMk7Fffv1harwwlzJciaEcijI_ACZd0YVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});